### ISSUE TITLE
tags are not compliant to default go mod version style

### ISSUE THREAD

**Issue by jonasbadstuebner** [jobstoit/hetzner-dns-go#5]
I was unable to reference the newly created tag `0.1.1` in the PR for external-dns. I think it is because there are guidelines to how a version tag is supposed to look like for go modules [here](https://go.dev/ref/mod#versions).
It states:
```
Each version starts with the letter v, followed by a semantic version.
[...]
For example, v0.0.0, v1.12.134, v8.0.5-pre, and v2.0.9+meta are valid versions.
```

Therefore, I think we need to create tag `v0.1.1` instead.

**Comment by jobstoit** [comment]
Got it, changed both tags to have a "v" before the versioning.
